name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: enter folder
      run: cd TKPEmu
    - name: configure
      run: cmake -B build
    - name: build
      run: cmake --build build
