name: Build Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev libtbb-dev libboost-all-dev build-essential gcc-12 g++-12 ninja-build qt6-base-dev libfmt-dev libqt6openglwidgets6 libqt6widgets6 libqt6opengl6 libqt6gui6
    - name: configure
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12
        sudo update-alternatives --set gcc /usr/bin/gcc-12
        cmake -S hydra -B hydra/build -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: make
      run: cmake --build hydra/build
