name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update-apt-get
      run: sudo apt-get update
    - name: install-deps
      run: sudo apt-get install libsdl2-dev libtbb-dev libboost-all-dev build-essential g++12
    - name: configure
      run: cmake -S TKPEmu -B TKPEmu/build
    - name: make
      run: cmake --build TKPEmu/build
