name: Build FreeBSD
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y curl cmake libX11 libXi libXrandr libXinerama libXcursor libglvnd alsa-lib
          run: |
            cmake -B build -GNinja
            cmake --build build --config Release
      - name: Release
        uses: actions/upload-artifact@v2
        with:
           name: FreeBSDRelease
           path: build/
