name: Build Linux
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
          sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev libasound2-dev
      - name: Build
        run: |
          cmake -B build -GNinja
          cmake --build build --config Release
      - name: Release
        uses: actions/upload-artifact@v2
        with:
           name: LinuxRelease
           path: build/