name: Build macOS
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 
      - name: Build
        run: |
          cmake -B build -GNinja
          cmake --build build--config Release
      - name: Build DMG
        run: |
          cd build
          brew install graphicsmagick imagemagick
          pip install setuptools
          npm install --global create-dmg
          create-dmg --dmg-title=hydra 'hydra.app' || true
          mv hydra*.dmg "hydra.dmg"
      - name: GH Release 🚀
        uses: actions/upload-artifact@v2
        with:
           name: MacOSRelease
           path: build/hydra.dmg
