name: Build MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install-deps
      run: brew install qt6 fmt googletest
    - name: configure
      run: cmake -B build 
    - name: make
      run: cmake --build build