name: Build MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: install-deps
      run: brew install qt6 ninja
    - name: configure
      run: cmake -B build -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: make
      run: cmake --build build