name: Regression Finder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: echo "BAR"
    - name: Find those regressions
      uses: OFFTKP/emulator-regression-finder@v1
