name: Build Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install-qt
      uses: jurplel/install-qt-action@v3.2.1
      with:
        version: '6.2.*'
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: clang-format
      run: |
        ./scripts/check_clang_format.sh
    - name: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev ninja-build liblua5.3-dev
    - name: configure
      run: CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12 cmake -B build -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: make
      run: cmake --build build --target hydra
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: Linux executable
        path: './build/hydra'