name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install-qt
      uses: jurplel/install-qt-action@v3.2.1
      with:
        version: '6.2.*'
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: install-deps
      run: vcpkg install --triplet x64-windows gtest lua
    - name: configure
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
    - name: make
      run: cmake --build build --target hydra --config Release
