name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install-qt
      uses: jurplel/install-qt-action@v3.2.1
      with:
        version: '6.2.*'
    - uses: actions/checkout@v3
    - name: install-deps
      run: vcpkg install --triplet x64-windows fmt gtest 
    - name: configure
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -T ClangCL
    - name: make
      run: cmake --build build
