name: Build Windows
jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Build 
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -B build
          cmake --build build --config Release
      - name: Release
        uses: actions/upload-artifact@v2
        with:
           name: WindowsRelease
           path: build/
